# --------------------------------------------------
# Generated by ChatGPT
# --------------------------------------------------

#!/bin/bash
set -e  # Stop if any command fails

# --- Resolve important paths ---
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$( dirname "$SCRIPT_DIR" )"
TEMPLATE="$SCRIPT_DIR/job_template.pbs"

echo "=== Project root: $PROJECT_DIR ==="
echo "=== Using template: $TEMPLATE ==="

# --- Load modules needed for compilation ---
module load GCC/13.2.0 CMake/3.27.6-GCCcore-13.2.0 OpenMPI/4.1.6-GCC-13.2.0

# --- Rebuild project ---
echo "=== Recompiling project ==="
cd "$PROJECT_DIR"
mkdir -p build bin
rm -r build bin
cmake -B build
cmake --build build
echo "=== Build completed ==="

# --- Experiment parameters ---
DATASETS=("gaussian")
SIZES=(4096 8192 16384)
RANKS_LIST=(1 2 4 8 16 32)

# --- Submit jobs ---
for DATA in "${DATASETS[@]}"; do

  if [ "$DATA" = "gaussian" ]; then
    PREFIX="g"
  else
    PREFIX="m"
  fi

  for SIZE in "${SIZES[@]}"; do
    for RANKS in "${RANKS_LIST[@]}"; do

      JOB_FILE="$SCRIPT_DIR/job_${DATA}_${SIZE}_r${RANKS}.pbs"
      JOB_NAME="${PREFIX}_${SIZE}_r${RANKS}"

      sed \
        -e "s/__RANKS__/${RANKS}/" \
        -e "s/\${DATA}/${DATA}/g" \
        -e "s/\${SIZE}/${SIZE}/g" \
        -e "s/\${RANKS}/${RANKS}/g" \
        "$TEMPLATE" > "$JOB_FILE"

      echo "Submitting $JOB_NAME"
      qsub -N "$JOB_NAME" "$JOB_FILE"

    done
  done
done

echo "=== All jobs submitted successfully ==="
