# --------------------------------------------------
# Generated by ChatGPT
# --------------------------------------------------

#!/bin/bash
set -e  # stop if any command fails

PROJECT_DIR="$HOME/hpc-project"

echo "=== Recompiling project ==="
cd "$PROJECT_DIR"

module load GCC/13.2.0 CMake/3.27.6-GCCcore-13.2.0 OpenMPI/4.1.6-GCC-13.2.0

rm -rf build bin
cmake -B build
cmake --build build

echo "=== Build completed ==="
cd "$PBS_O_WORKDIR" 2>/dev/null || cd -

DATASETS=("gaussian" "mixed")
SIZES=(8192 32768 131072)
RANKS_LIST=(1 2 4 8 16 32)

TEMPLATE="job_template.pbs"

for DATA in "${DATASETS[@]}"; do

  if [ "$DATA" = "gaussian" ]; then
    PREFIX="g"
  else
    PREFIX="m"
  fi

  for SIZE in "${SIZES[@]}"; do
    for RANKS in "${RANKS_LIST[@]}"; do

      JOB_FILE="job_${DATA}_${SIZE}_r${RANKS}.pbs"
      JOB_NAME="${PREFIX}_${SIZE}_r${RANKS}"

      sed \
        -e "s/__RANKS__/${RANKS}/" \
        -e "s/\${DATA}/${DATA}/g" \
        -e "s/\${SIZE}/${SIZE}/g" \
        -e "s/\${RANKS}/${RANKS}/g" \
        "$TEMPLATE" > "$JOB_FILE"

      echo "Submitting $JOB_NAME"
      qsub -N "$JOB_NAME" "$JOB_FILE"

    done
  done
done

echo "=== All jobs submitted ==="
