# --------------------------------------------------
# Generated by ChatGPT
# --------------------------------------------------

import os
import sys
import csv
from sklearn.metrics import adjusted_rand_score


def read_labels(csv_path):
    """Read labels (last column) from a CSV file."""
    labels = []

    with open(csv_path, newline='') as f:
        reader = csv.reader(f)
        header = next(reader)  # skip header

        for row in reader:
            if not row:
                continue
            labels.append(int(row[-1]))  # last column = label

    return labels


def evaluate_folders(gt_folder, pred_folder):
    """Compare matching CSV files in two folders using ARI."""
    gt_files = sorted(f for f in os.listdir(gt_folder) if f.endswith(".csv"))
    pred_files = sorted(f for f in os.listdir(pred_folder) if f.endswith(".csv"))

    scores = []

    print("\n=== ARI Evaluation Per File ===\n")

    for filename in gt_files:
        gt_path = os.path.join(gt_folder, filename)
        pred_path = os.path.join(pred_folder, filename)

        if not os.path.exists(pred_path):
            print(f"Missing prediction file for: {filename}")
            continue

        gt_labels = read_labels(gt_path)
        pred_labels = read_labels(pred_path)

        if len(gt_labels) != len(pred_labels):
            print(f"Different number of points in file: {filename}")
            continue

        ari = adjusted_rand_score(gt_labels, pred_labels)
        scores.append(ari)

        print(f"{filename:30s} ARI = {ari:.4f}  ({ari * 100:.2f}%)")

    if scores:
        mean_ari = sum(scores) / len(scores)
        print("\n=== Overall Accuracy ===")
        print(f"Mean ARI: {mean_ari:.4f}  ({mean_ari * 100:.2f}%)")
    else:
        print("\nNo valid file pairs were evaluated.")


def main():
    if len(sys.argv) != 3:
        print("Usage: python evaluate_ari.py <ground_truth_folder> <prediction_folder>")
        sys.exit(1)

    gt_folder = sys.argv[1]
    pred_folder = sys.argv[2]

    evaluate_folders(gt_folder, pred_folder)


if __name__ == '__main__':
    main()
