# --------------------------------------------------
# Generated by ChatGPT
# --------------------------------------------------

import numpy as np
import pyvista as pv
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap


def parse_points(file) -> np.ndarray:
    lines = file.read().strip().splitlines()
    header = lines[0].strip().split(',')
    lines = lines[1:]

    has_labels = len(header) >= 4

    data = []
    for line in lines:
        parts = line.split(',')
        if has_labels:
            x, y, z, label = parts
            data.append([float(x), float(y), float(z), float(label)])
        else:
            x, y, z = parts[:3]
            data.append([float(x), float(y), float(z)])

    return np.array(data), has_labels


def generate_distinct_colors(n):
    """Generate n visually distinct colors using evenly spaced hues."""
    hues = np.linspace(0, 1, n, endpoint=False)
    colors = plt.cm.hsv(hues)[:, :3]  # Remove alpha channel
    np.random.shuffle(colors)         # Avoid similar adjacent colors
    return ListedColormap(colors)


def plot_points(points: np.ndarray, has_labels: bool):
    coords = points[:, :3].astype(float)

    cloud = pv.PolyData(coords)
    sphere_geom = pv.Sphere(radius=0.125)

    plotter = pv.Plotter()
    plotter.set_background("white")

    if has_labels:
        labels = points[:, 3].astype(int)

        # Remap labels to consecutive IDs (important for good color spacing)
        unique_labels = np.unique(labels)
        label_map = {old: new for new, old in enumerate(unique_labels)}
        labels = np.vectorize(label_map.get)(labels)

        cloud["labels"] = labels
        n_clusters = len(unique_labels)

        cmap = generate_distinct_colors(n_clusters)
        geom_points = cloud.glyph(geom=sphere_geom, scale=False)

        plotter.add_mesh(
            geom_points,
            scalars="labels",
            cmap=cmap,
            categories=False,
            show_scalar_bar=False,
            smooth_shading=True
        )
    else:
        geom_points = cloud.glyph(geom=sphere_geom, scale=False)
        plotter.add_mesh(
            geom_points,
            color="lightblue",
            smooth_shading=True
        )

    plotter.view_xy()
    plotter.add_axes()
    plotter.reset_camera()
    plotter.show()
    plotter.close()

    print(f"Coords shape: {coords.shape}")
    print(f"Data range: {coords.min(axis=0)} to {coords.max(axis=0)}")


def main():
    from argparse import ArgumentParser

    args = ArgumentParser()
    args.add_argument(
        '-i', '--input-file',
        help='input csv file',
        required=True,
        dest='input_file',
        type=str
    )
    pargs = args.parse_args()

    with open(pargs.input_file, 'r') as file:
        points, has_labels = parse_points(file)
        print(f"Opened file: {pargs.input_file}")
        plot_points(points, has_labels)


if __name__ == '__main__':
    main()
